### ISSUE TITLE
Publish Provider to Terraform Registry

### ISSUE THREAD

**Issue by dehume** [MaterializeInc/terraform-provider-materialize#4]
To make it easier for users to install. We should publish the provider to the Terraform Registry. Will need to work in the versioning and publishing into a Github Action

https://developer.hashicorp.com/terraform/registry/providers/publishing

**Comment by benesch** [comment]
I got this set this up for the Frontegg Terraform provider (back when that was our project rather than an official Frontegg project), and it went pretty smoothly. (See e.g. https://github.com/frontegg/terraform-provider-frontegg.) Let me know when you're ready to take this step and I can help with getting the GPG keys wired up, etc.
